#!/usr/bin/env bash

if ! brew ls --cask nikitabobko/tap/aerospace > /dev/null; then
	echo "⭕️ Installing aerospace"
	brew install --cask nikitabobko/tap/aerospace
else
	echo "✅ Aerospace already installed"
fi
