#!/usr/bin/env bash

#--------------- INSTALL GHOSTTY
if ! brew ls --versions ghostty 2> /dev/null; then
  brew install --cask ghostty
else
  echo "Ghostty already installed!"
fi

#--------------- INSTALL TMUX
if ! brew ls --versions tmux 2> /dev/null; then
  brew install tmux
else
  echo "Ghostty already installed!"
fi

#--------------- INSTALL PROMPT
if ! brew ls --versions jandedobbeleer/oh-my-posh/oh-my-posh 2> /dev/null; then
  brew install jandedobbeleer/oh-my-posh/oh-my-posh
else
  echo "oh-my-posh already installed!"
fi

# add init to enviroment variable
INIT_OMP='if [ "$TERM_PROGRAM" != "Apple_Terminal" ]; then
  eval "$(oh-my-posh init zsh --config $HOME/.config/ohmyposh/myomp.toml)"
fi'

PROFILE="$HOME/.zshrc"

if ! grep -Fxq "$INIT_OMP" "$PROFILE"; then
	echo "$INIT_OMP" >> "$PROFILE"
	echo "Enviroment var added for OMP"
fi
