#!/usr/bin/env bash

FORMULA=("tmux" "jandedobbeleer/oh-my-posh/oh-my-posh")
CASK=("ghostty") 

for formulae in "${CASK[@]}"
do 
  if ! brew ls --cask $formulae > /dev/null; then
    brew install --cask $formulae 
  else
    echo "✅ $formulae already installed!"
  fi
done

for formulae in "${FORMULA[@]}"
do
  if ! brew ls --versions $formulae > /dev/null; then
    brew install $formulae 
  else
    echo "✅ $formulae already installed!"
  fi
done

# add init to enviroment variable
if brew ls --versions jandedobbeleer/oh-my-posh/oh-my-posh > /dev/null; then
  INIT_OMP='if [ "$TERM_PROGRAM" != "Apple_Terminal" ]; then
    eval "$(oh-my-posh init zsh --config $HOME/.config/ohmyposh/myomp.toml)"
  fi'

  PROFILE="$HOME/.zshrc"

  if ! grep -Fxq "$INIT_OMP" "$PROFILE"; then
    echo "$INIT_OMP" >> "$PROFILE"
    # check configuration was applied
    if ! grep -Fxq "$INIT_OMP" "$PROFILE"; then
	  echo "> ✅ jandedobbeleer/oh-my-posh/oh-my-posh configured!"
    else
	    echo "> ⛔️ failed to configure jandedobbeleer/oh-my-posh/oh-my-posh!"
    fi
  else
	  echo "> ✅ jandedobbeleer/oh-my-posh/oh-my-posh already configured!"
  fi
fi
