#!/usr/bin/env bash

dry="0"

script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

if [[ $1 == "--dry" ]]; then
	dry="1"
fi	

log() {
	if [[ $dry == "1" ]]; then
		echo "[DRY_RUN]: $@"
	else
		echo  "$@"
	fi
}

execute() {
	log "execute $@"
	if [[ $dry == "1" ]]; then
		return
	fi

	"$@"
}

log $script_dir

copy_dir() {
	from=$1
	to=$2
 
	pushd $from > /dev/null
	dirs=$(find . -maxdepth 1 -mindepth 1 -type d)
	for dir in $dirs; do
		execute rm -rf $to/$dir
		execute cp -r $dir $to/$dir
	done
	popd > /dev/null
}

copy_file() {
	from=$1
	to=$2
	name=$(basename $from)

	execute rm $to/$name
	execute cp $from $to/$name
}

copy_dir .local $HOME/.local
copy_dir .config $HOME/.config
# copy_file .config $HOME/.config
