#!/usr/bin/env bash

dry="0"

# while there are arguments, loop through and shift
# if the arg is "--dry"
if [[ $1 == "--dry" ]]; then
	dry="1"
fi	

log() {
	if [[ $dry == "1" ]]; then
		echo "[DRY_RUN]: $@"
	else
		echo  "$@"
	fi
}

execute() {
	log "execute $@"
	if [[ $dry == "1" ]]; then
		return
	fi

	"$@"
}

log "======================= dev-env =============================="

copy_dir() {
	from=$1
	to=$2
 
	log "FROM: $from"
	log "TO: $to"
	pushd $from
	dirs=$(find . -maxdepth 1 -mindepth 1 -type d)
	for dir in $dirs; do
		execute rm -rf $to/$dir
		execute cp -r $dir $to/$dir
	done
	popd
}

copy_dir .config "$HOME/.config"

ls -la $HOME/.config

log "======================= dev-env =============================="